services:
  backend:
    build: backend
    depends_on:
      database:
      condition: service_healthy
    ports:
      - "3000:3000"
  frontend:
    build: web
    ports:
      - "8080:80"
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      interval: 1s
      test: "pg_isready --username=postgres"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
