services:
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=postgres://postgres:secret12345@database:5432/postgres
    ports:
      - "3000:3000"
  frontend:
    build: web
    ports:
      - "8080:80"
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret12345
    healthcheck:
      interval: 1s
      test: "pg_isready --username=postgres"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
